services:
  - type: web
    name: your-backend-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret-key
        